api_url: http://13.210.97.155:8000
device_key: dTDsDA30I6xy2FYm5_VJzrv3Q7CrXAABt1t5y0_T3yM

buffer_seconds: 60
clip_seconds: 30
segment_seconds: 10
heartbeat_seconds: 30
button_cooldown_seconds: 2

data_dir: ./data

cameras:
  - index: 1
    name: Camera 1
    rtsp_url: test://local
    button:
      type: mock
      mock_file: ./data/button-1.trigger

  - index: 2
    name: Camera 2
    rtsp_url: test://local
    button:
      type: mock
      mock_file: ./data/button-2.trigger
