#!/usr/bin/env python3
"""Privileged installer for the Lance On capture agent (Ubuntu)."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote

INSTALL_DIR = Path("/opt/lance-on/capture")
CONFIG_DIR = Path("/etc/lance-on")
DATA_DIR = Path("/var/lib/lance-on")
CONFIG_PATH = CONFIG_DIR / "config.yaml"
SERVICE_PATH = Path("/etc/systemd/system/lanceon-capture.service")
DEFAULT_API_URL = "https://api.lanceonpara.com.br"

APT_PACKAGES = [
    "ffmpeg",
    "python3",
    "python3-venv",
    "python3-pip",
    "python3-tk",
    "python3-libgpiod",
    "libgpiod-dev",
    "rsync",
]


def log(message: str) -> None:
    print(message, flush=True)


def run(command: list[str], **kwargs) -> None:
    log("+ " + " ".join(command))
    subprocess.run(command, check=True, **kwargs)


def yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def rtsp_url(user: str, password: str, ip: str) -> str:
    return (
        f"rtsp://{quote(user, safe='')}:{quote(password, safe='')}@{ip.strip()}"
        ":554/cam/realmonitor?channel=1&subtype=0"
    )


def install_apt_packages() -> None:
    env = os.environ.copy()
    env["DEBIAN_FRONTEND"] = "noninteractive"
    run(["apt-get", "update", "-y"], env=env)
    run(["apt-get", "install", "-y", *APT_PACKAGES], env=env)


def copy_agent(source: Path) -> None:
    INSTALL_DIR.parent.mkdir(parents=True, exist_ok=True)
    if source.resolve() == INSTALL_DIR.resolve():
        log(f"Source is already {INSTALL_DIR}; skipping copy.")
        return

    log(f"Copying capture agent to {INSTALL_DIR}")
    if INSTALL_DIR.exists():
        shutil.rmtree(INSTALL_DIR)
    shutil.copytree(
        source,
        INSTALL_DIR,
        ignore=shutil.ignore_patterns(
            ".venv",
            "__pycache__",
            "*.pyc",
            ".git",
            ".gitignore",
        ),
    )


def install_python_deps() -> None:
    venv = INSTALL_DIR / ".venv"
    python = venv / "bin" / "python"
    pip = venv / "bin" / "pip"
    if not python.exists():
        run([sys.executable, "-m", "venv", str(venv)])
    run([str(pip), "install", "--upgrade", "pip"])
    run([str(pip), "install", "-r", str(INSTALL_DIR / "requirements.txt")])


def install_watermark(selected: str | None) -> Path:
    dest = INSTALL_DIR / "assets" / "video-watermark.jpeg"
    dest.parent.mkdir(parents=True, exist_ok=True)
    if selected:
        src = Path(selected).expanduser()
        if not src.is_file():
            raise FileNotFoundError(f"Watermark not found: {src}")
        shutil.copy2(src, dest)
        log(f"Watermark copied from {src}")
    elif not dest.exists():
        log("No watermark selected; clips will use the bundled default if present.")
    return dest


def write_config(settings: dict, watermark: Path) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    api_url = str(settings.get("api_url") or DEFAULT_API_URL).rstrip("/")
    device_key = str(settings["device_key"]).strip()
    user = str(settings.get("camera_user") or "admin").strip()
    password = str(settings["camera_password"])
    use_gpio = bool(settings.get("use_gpio", True))

    cameras = settings.get("cameras") or []
    camera_lines = []
    for item in cameras:
        index = int(item["index"])
        ip = str(item["ip"]).strip()
        url = rtsp_url(user, password, ip)
        camera_lines.append(
            "\n".join(
                [
                    f"  - index: {index}",
                    f"    name: Camera {index}",
                    f"    rtsp_url: {yaml_quote(url)}",
                ]
            )
        )

    button_block = (
        "button:\n  type: gpio\n  pin: 17\n"
        if use_gpio
        else "button:\n  type: none\n"
    )

    content = f"""# Generated by Lance On Setup
api_url: {yaml_quote(api_url)}
device_key: {yaml_quote(device_key)}

buffer_seconds: 300
clip_seconds: 30
segment_seconds: 10
heartbeat_seconds: 60
button_cooldown_seconds: 3

{button_block}
cameras:
{chr(10).join(camera_lines)}

data_dir: {yaml_quote(str(DATA_DIR))}
watermark_path: {yaml_quote(str(watermark))}
"""
    CONFIG_PATH.write_text(content, encoding="utf-8")
    os.chmod(CONFIG_PATH, 0o600)
    log(f"Wrote {CONFIG_PATH}")


def install_service() -> None:
    shutil.copy2(INSTALL_DIR / "lanceon-capture.service", SERVICE_PATH)
    run(["systemctl", "daemon-reload"])
    run(["systemctl", "enable", "lanceon-capture.service"])
    run(["systemctl", "restart", "lanceon-capture.service"])
    log("Service lanceon-capture enabled and started.")


def main() -> int:
    if os.geteuid() != 0:
        print("This installer must run as root (pkexec/sudo).", file=sys.stderr)
        return 1

    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, help="Path to the capture folder")
    parser.add_argument("--settings", required=True, help="JSON settings from the Setup App")
    args = parser.parse_args()

    source = Path(args.source).resolve()
    settings_path = Path(args.settings)
    settings = json.loads(settings_path.read_text(encoding="utf-8"))

    if not str(settings.get("device_key", "")).strip():
        raise SystemExit("Device key is required.")
    cameras = settings.get("cameras") or []
    if not cameras:
        raise SystemExit("At least one camera IP is required.")

    log("Installing system packages (FFmpeg, Python, GPIO)...")
    install_apt_packages()
    copy_agent(source)
    log("Installing Python packages...")
    install_python_deps()
    watermark = install_watermark(settings.get("watermark_path"))
    write_config(settings, watermark)
    install_service()
    log("INSTALL_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
